remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
title: React Native für Einsteiger
description: In diesem Teil der Talkreihe wird die Entwicklungsumgebung für React Native eingerichtet. Wir schauen uns an, wie wir React Native mit Expo entwickeln können. Außerdem wird erklärt, wie wir React Native ohne Expo entwickeln können.
show_downloads: true
